"""Add ON DELETE CASCADE to room join requests

Revision ID: 10fd44aff1fb
Revises: c62aeef1befb
Create Date: 2025-06-13 15:05:06.040989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10fd44aff1fb'
down_revision: Union[str, None] = 'c62aeef1befb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_join_requests', sa.Column('requested_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_room_join_requests_id'), 'room_join_requests', ['id'], unique=False)
    op.drop_constraint(op.f('room_join_requests_room_id_fkey'), 'room_join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'room_join_requests', 'game_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('room_join_requests', 'status')
    op.drop_column('room_join_requests', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_join_requests', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('room_join_requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room_join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('room_join_requests_room_id_fkey'), 'room_join_requests', 'game_rooms', ['room_id'], ['id'])
    op.drop_index(op.f('ix_room_join_requests_id'), table_name='room_join_requests')
    op.drop_column('room_join_requests', 'requested_at')
    # ### end Alembic commands ###
