"""add user_code

Revision ID: 2b5a55fbdc96
Revises: d0c103381c4e
Create Date: 2025-06-12 11:58:34.339491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5a55fbdc96'
down_revision: Union[str, None] = 'd0c103381c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_column('users', 'user_code')
    # ### end Alembic commands ###
