"""Add cascade delete to room_join_requests.room_id

Revision ID: 34e20dfe0643
Revises: b25e28067b5b
Create Date: 2025-06-13 15:15:39.715394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e20dfe0643'
down_revision: Union[str, None] = 'b25e28067b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_join_requests_id'), table_name='room_join_requests')
    op.drop_table('room_join_requests')
    op.add_column('game_room_users', sa.Column('status', sa.String(), nullable=True))
    op.add_column('game_room_users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('game_room_users', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_room_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_game_room_users_id'), table_name='game_room_users')
    op.drop_constraint(op.f('game_room_users_room_id_fkey'), 'game_room_users', type_='foreignkey')
    op.create_foreign_key(None, 'game_room_users', 'game_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_room_users', type_='foreignkey')
    op.create_foreign_key(op.f('game_room_users_room_id_fkey'), 'game_room_users', 'game_rooms', ['room_id'], ['id'])
    op.create_index(op.f('ix_game_room_users_id'), 'game_room_users', ['id'], unique=False)
    op.alter_column('game_room_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_room_users', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('game_room_users', 'timestamp')
    op.drop_column('game_room_users', 'status')
    op.create_table('room_join_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], name=op.f('room_join_requests_room_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('room_join_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_join_requests_pkey'))
    )
    op.create_index(op.f('ix_room_join_requests_id'), 'room_join_requests', ['id'], unique=False)
    # ### end Alembic commands ###
