"""add user_code

Revision ID: 3538728bdf54
Revises: 2b5a55fbdc96
Create Date: 2025-06-12 12:06:46.431647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3538728bdf54'
down_revision: Union[str, None] = '2b5a55fbdc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buddy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['buddy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'buddy_id')
    # ### end Alembic commands ###
