"""add descripton

Revision ID: 62adec3ce1d9
Revises: 53baea6c7862
Create Date: 2025-05-27 13:49:11.238846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62adec3ce1d9'
down_revision: Union[str, None] = '53baea6c7862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rooms', 'description')
    # ### end Alembic commands ###
