"""GameRoom

Revision ID: 80f1d02f557c
Revises: 56f95ae18e1b
Create Date: 2025-05-27 12:42:25.277206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80f1d02f557c'
down_revision: Union[str, None] = '56f95ae18e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'game_rooms', ['name'])
    op.drop_constraint('game_rooms_player_black_id_fkey', 'game_rooms', type_='foreignkey')
    op.drop_constraint('game_rooms_player_white_id_fkey', 'game_rooms', type_='foreignkey')
    op.drop_column('game_rooms', 'is_active')
    op.drop_column('game_rooms', 'player_black_id')
    op.drop_column('game_rooms', 'created_at')
    op.drop_column('game_rooms', 'player_white_id')
    op.drop_column('game_rooms', 'fen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('fen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('game_rooms', sa.Column('player_white_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_rooms', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('game_rooms', sa.Column('player_black_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_rooms', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_rooms_player_white_id_fkey', 'game_rooms', 'users', ['player_white_id'], ['id'])
    op.create_foreign_key('game_rooms_player_black_id_fkey', 'game_rooms', 'users', ['player_black_id'], ['id'])
    op.drop_constraint(None, 'game_rooms', type_='unique')
    op.drop_column('game_rooms', 'name')
    # ### end Alembic commands ###
