"""Add cascade delete to room_join_requests.room_id

Revision ID: 8314e64c061b
Revises: 34e20dfe0643
Create Date: 2025-06-13 15:22:09.044983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8314e64c061b'
down_revision: Union[str, None] = '34e20dfe0643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_room_users', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_room_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_game_room_users_id'), 'game_room_users', ['id'], unique=False)
    op.drop_constraint(op.f('game_room_users_room_id_fkey'), 'game_room_users', type_='foreignkey')
    op.create_foreign_key(None, 'game_room_users', 'game_rooms', ['room_id'], ['id'])
    op.drop_column('game_room_users', 'status')
    op.drop_column('game_room_users', 'timestamp')
    op.drop_constraint(op.f('room_join_requests_room_id_fkey'), 'room_join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'room_join_requests', 'game_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('room_join_requests_room_id_fkey'), 'room_join_requests', 'game_rooms', ['room_id'], ['id'])
    op.add_column('game_room_users', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('game_room_users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_room_users', type_='foreignkey')
    op.create_foreign_key(op.f('game_room_users_room_id_fkey'), 'game_room_users', 'game_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_game_room_users_id'), table_name='game_room_users')
    op.alter_column('game_room_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_room_users', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
