"""Add Friendship PrivateMessage  table

Revision ID: 8651bb37a554
Revises: 858d6767d05e
Create Date: 2025-05-31 13:32:58.120896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8651bb37a554'
down_revision: Union[str, None] = '858d6767d05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_user_friend_uc'), 'friendships', type_='unique')
    op.drop_constraint(op.f('friendships_user_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_friend_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['friend_id'], ['id'])
    op.drop_column('friendships', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_friend_id_fkey'), 'friendships', 'users', ['friend_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('friendships_user_id_fkey'), 'friendships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('_user_friend_uc'), 'friendships', ['user_id', 'friend_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
