"""add blocks table with unique constraint

Revision ID: 92ee31845e25
Revises: a90f217e18c6
Create Date: 2025-06-13 12:14:03.934489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ee31845e25'
down_revision: Union[str, None] = 'a90f217e18c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_block_pair', 'blocks', ['blocker_id', 'blocked_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_block_pair', 'blocks', type_='unique')
    # ### end Alembic commands ###
