"""Add user

Revision ID: a6961cafe98b
Revises: f1cfb4e28dea
Create Date: 2025-06-18 13:46:02.298164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6961cafe98b'
down_revision: Union[str, None] = 'f1cfb4e28dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'message_id')
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'is_online')
    op.add_column('notifications', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
