"""Add private message

Revision ID: c15c20f91863
Revises: d8df17b4a482
Create Date: 2025-06-17 15:23:13.443351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15c20f91863'
down_revision: Union[str, None] = 'd8df17b4a482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_messages', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_messages', 'read')
    # ### end Alembic commands ###
