"""add guild member model

Revision ID: c7ffb2c59564
Revises: 999b1c8d1b94
Create Date: 2025-05-27 21:08:06.964342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ffb2c59564'
down_revision: Union[str, None] = '999b1c8d1b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_members', sa.Column('role', sa.String(), nullable=True))
    op.add_column('guild_members', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_members', 'online')
    op.drop_column('guild_members', 'role')
    # ### end Alembic commands ###
