"""Initial migration

Revision ID: d20b00e24a28
Revises: 80f1d02f557c
Create Date: 2025-05-27 12:49:04.824536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20b00e24a28'
down_revision: Union[str, None] = '80f1d02f557c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('game_rooms', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('game_rooms_name_key', 'game_rooms', type_='unique')
    op.create_foreign_key(None, 'game_rooms', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_rooms', type_='foreignkey')
    op.create_unique_constraint('game_rooms_name_key', 'game_rooms', ['name'])
    op.drop_column('game_rooms', 'created_at')
    op.drop_column('game_rooms', 'created_by')
    # ### end Alembic commands ###
