"""Add notification

Revision ID: d8df17b4a482
Revises: 086201d3313d
Create Date: 2025-06-17 13:43:34.905465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8df17b4a482'
down_revision: Union[str, None] = '086201d3313d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buddy_requests', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('buddy_requests', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buddy_requests', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('buddy_requests', 'timestamp')
    # ### end Alembic commands ###
