"""Add ludo

Revision ID: dcd6fb556939
Revises: 72ece9af213a
Create Date: 2025-06-29 13:47:59.304604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd6fb556939'
down_revision: Union[str, None] = '72ece9af213a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ludo_games_room_id_key'), 'ludo_games', type_='unique')
    op.drop_constraint(op.f('ludo_games_room_id_fkey'), 'ludo_games', type_='foreignkey')
    op.create_foreign_key(None, 'ludo_games', 'game_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ludo_games', type_='foreignkey')
    op.create_foreign_key(op.f('ludo_games_room_id_fkey'), 'ludo_games', 'game_rooms', ['room_id'], ['id'])
    op.create_unique_constraint(op.f('ludo_games_room_id_key'), 'ludo_games', ['room_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
