"""Add coins, xp, level, high_score, last_daily_claim

Revision ID: e2613936ebf5
Revises: 56d1d4dcef96
Create Date: 2025-06-10 13:56:36.360164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2613936ebf5'
down_revision: Union[str, None] = '56d1d4dcef96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
