"""Add guild_id to user

Revision ID: e8cb8d17f48e
Revises: 8be1c8eb028c
Create Date: 2025-06-12 13:01:53.980336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cb8d17f48e'
down_revision: Union[str, None] = '8be1c8eb028c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guild_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'guild_id')
    # ### end Alembic commands ###
