"""Add private message

Revision ID: f1cfb4e28dea
Revises: c15c20f91863
Create Date: 2025-06-17 16:55:14.994499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cfb4e28dea'
down_revision: Union[str, None] = 'c15c20f91863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('related_user_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'message_id')
    op.drop_column('notifications', 'related_user_id')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
