"""Add Friendship   table

Revision ID: f22fadf018dd
Revises: 32851f0bbfaa
Create Date: 2025-05-31 17:13:59.375889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f22fadf018dd'
down_revision: Union[str, None] = '32851f0bbfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.alter_column('friendships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friendships', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('friendships_user_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_friend_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['friend_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['user_id'], ['id'])
    op.drop_column('friendships', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_friend_id_fkey'), 'friendships', 'users', ['friend_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('friendships_user_id_fkey'), 'friendships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('friendships', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('friendships', 'accepted')
    # ### end Alembic commands ###
